ResultMode: Unredeemed
OutputPath: "%CURRENT_DIR%\\output\\"
HumbleOptions:
  AllowedTypes:
    - Steam
  AllowExpired: false
SteamOptions:
  ApiKey: 4240C1ACFCB80783AEBD5E40B055AA57
  SteamId: 76561198147867236