ResultMode: Unredeemed
OutputPath: "%CURRENT_DIR%\\output\\"
HumbleOptions:
  AuthToken: eyJ1c2VyX2lkIjo1MTExMzIxMTQxOTY4ODk2LCJpZCI6InJwYVE5NGNDUkgiLCJhdXRoX3RpbWUiOjE2NTg0MjgyNjZ9|1659117090|86f3489059690f1873a37e9f81c9a40c9d695b8e
  AllowedTypes:
    - Steam
  AllowExpired: false
SteamOptions:
  ApiKey: 4240C1ACFCB80783AEBD5E40B055AA57
  SteamId: 76561198147867236